#!/usr/bin/bash
JUPYTER="/c/ProgramData/Anaconda3/Scripts/jupyter"


[ "$(git diff --cached --name-only **/*.ipynb|wc -l)" == 0 ] && exit 0

$JUPYTER nbconvert --ClearOutputPreprocessor.enabled=True --inplace $(git diff --cached --name-only **/*.ipynb) \
&& git add $(git diff --cached --name-only) \
&& exit $?
